### ISSUE TITLE
Error 104 1970

### ISSUE THREAD

**Issue by TheRDroyale** [PretendoNetwork/error-codes#4]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

I was trying to play Splatoon,but it gave this error,I tried to reinstall nimble,delete the shared save data,but it doesn't work

### What did you expect to happen?

I expected it to open the lobby

**Comment by jonbarrow** [comment]
I'm not sure why I approved this. This isn't a valid issue for this repository. As described, this repository is strictly for holding metadata about error codes, it has nothing to do with individual services. Please report any and all issues to the *correct* repository
